In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
from PIL import Image
import os
import seaborn as sns
import matplotlib.pyplot as plt
from pathlib import Path

In [ ]:
#load the all the images lcoated int eh folder dill and convert them to numpy arrays

all_images = []
for filename in os.listdir("/home/jouell/code/jouell3/plant_detect/data/raw/dill"):
    if filename.endswith(".jpg"):     
        image = Image.open("/home/jouell/code/jouell3/plant_detect/data/raw/dill/" + filename)
        # save the image with a new name
        #with Image.open("/home/jouell/code/jouell3/plant_detect/data/raw/dill/" + filename) as img:
        #    img.save("/home/jouell/code/jouell3/plant_detect/data/raw/dill/" + f"dill_{filename}")
        image_np = np.array(image)
        all_images.append(image_np)
all_images = np.array(all_images)
all_images.shape

In [ ]:
## this allow allow to rename all teh images located in a folder with the name of the folder as prefix, for example dill_0.jpg, dill_1.jpg, etc.



folder = Path("/home/jouell/code/jouell3/plant_detect/data/raw/lavender")
prefix = folder.name

for path in sorted(folder.glob("*.jpg")):
    if not path.stem.startswith(f"{prefix}_"):  # skip already-renamed files
        new_path = path.parent / f"{prefix}_{path.name}"
        path.rename(new_path)
        print(f"{path.name} → {new_path.name}")

print("Done.")

In [ ]:
labels = pd.read_csv("/home/jouell/code/jouell3/plant_detect/data/labels.csv")
labels.head()

In [ ]:
labels_3 = pd.read_csv("/home/jouell/code/jouell3/plant_detect/data/labels.csv")
labels_3.head()

In [ ]:
project_root = Path("/home/jouell/code/jouell3/plant_detect")
out_dir = project_root / "data/dataset_aromatic_plants/all_images"
out_dir.mkdir(parents=True, exist_ok=True)



for i, row in labels_3.iterrows():
    src = project_root / row.filename
    dst = out_dir / Path(row.filename).name
    with Image.open(src) as image:
        image.save(dst)

In [ ]:
labels.to_csv(project_root / "data/labels2.csv", index=False)

In [ ]:
labels_2 = pd.read_csv("/home/jouell/code/jouell3/plant_detect/data/labels2.csv")
labels_2.head()

In [ ]:
for i, row in enumerate(labels_2.itertuples()):
    name = row.filename.split("/")[-1]
    new_name = name.split("_")[0]
    labels_2.at[i, 'name'] = new_name
    print(labels_2.at[i, 'name'])

In [ ]:
labels_2.to_csv("/home/jouell/code/jouell3/plant_detect/data/labels2.csv", index=False)

In [ ]:
new_images = pd.read_csv("/home/jouell/code/jouell3/plant_detect/data/dataset_aromatic_plants/dataset_fennel.csv")
new_images.head()

In [ ]:
files_df = []
name = "fennel"
IMAGE_PATH = "/home/jouell/code/jouell3/plant_detect/data/dataset_aromatic_plants/fennel4/"
project_root = Path("/home/jouell/code/jouell3/plant_detect")
for i, row in new_images.iterrows():
    src = IMAGE_PATH + row.image_path.split("/")[-1]
    dst = project_root / "data/dataset_aromatic_plants/all_images2" / row.image_path.split("/")[-1]
    files_df.append({'filename': row.image_path.split("/")[-1], 'name': name})
    with Image.open(src) as image:
        image.save(dst)

In [ ]:
pd.DataFrame(files_df).to_csv("/home/jouell/code/jouell3/plant_detect/data/dataset_aromatic_plants/dataset_fennel2.csv", index=False)

In [10]:
#combining all the dataset with the name labels into one dataset
# files are either located in the folders data/dataset_flowers or data/dataset_fruits
# we first need to grab all teh csv files thata re located within these folder and contains the labels_*.csv in their name and then combine them into one dataset


for folder in ["../data/dataset_flowers", "../data/dataset_fruits"]:
    all_labels = []
    for filename in os.listdir(folder):
        if filename.startswith("labels_") and filename.endswith(".csv"):
            df = pd.read_csv(os.path.join(folder, filename))
            split_filename = filename.split("_")[1]
            plant_name = split_filename.split(".")[0]  # get the plant name from the filename
            df["filename"] = df["filename"].apply(lambda x: os.path.join(plant_name, x))
            all_labels.append(df)
    combined_labels = pd.concat(all_labels, ignore_index=True)
    combined_labels.to_csv(os.path.join(folder, "dataset_combined.csv"), index=False)

In [22]:
labels_3 = pd.read_csv("/home/jouell/code/jouell3/plant_detect2/data/dataset_flowers/dataset_combined.csv")
labels_3.head()

                       filename label       name
0  hellebore/hellebore_0003.jpg  good  hellebore
1  hellebore/hellebore_0004.jpg  good  hellebore
2  hellebore/hellebore_0006.jpg  good  hellebore
3  hellebore/hellebore_0010.jpg  good  hellebore
4  hellebore/hellebore_0011.jpg  good  hellebore

In [23]:
project_root = Path("/home/jouell/code/jouell3/plant_detect2/data/dataset_flowers")
out_dir = project_root / "all_images"
out_dir.mkdir(parents=True, exist_ok=True)



for i, row in labels_3.iterrows():
    src = project_root / row.filename
    dst = out_dir / Path(row.filename).name
    with Image.open(src) as image:
        image.save(dst)

In [26]:
labels_4 = pd.read_csv("/home/jouell/code/jouell3/plant_detect2/data/dataset_fruits/dataset_combined.csv")
labels_4.head()

                       filename label       name
0  blueberry/blueberry_0006.jpg  good  blueberry
1  blueberry/blueberry_0010.jpg  good  blueberry
2  blueberry/blueberry_0013.jpg  good  blueberry
3  blueberry/blueberry_0015.jpg  good  blueberry
4  blueberry/blueberry_0018.jpg  good  blueberry

In [27]:
project_root2 = Path("/home/jouell/code/jouell3/plant_detect2/data/dataset_fruits")
out_dir = project_root2 / "all_images"
out_dir.mkdir(parents=True, exist_ok=True)



for i, row in labels_4.iterrows():
    src = project_root2 / row.filename
    dst = out_dir / Path(row.filename).name
    with Image.open(src) as image:
        image.save(dst)

In [28]:
all_labels = pd.concat([labels_3, labels_4], ignore_index=True)
all_labels.to_csv("/home/jouell/code/jouell3/plant_detect2/data/all_labels.csv", index=False)

In [30]:
all_labels['name'].value_counts()/len(all_labels)

name
cosmos           0.040120
lisianthus       0.039745
poppy            0.039620
zinnia           0.038620
gerbera          0.037370
fig              0.037370
grape            0.035996
strawberry       0.034996
raspberry        0.033121
blackberry       0.032496
bird             0.031621
blueberry        0.031621
avocado          0.031496
lemon            0.031371
sunflower        0.030871
melon            0.030621
ranunculus       0.029746
kiwi             0.029621
freesia          0.029121
daisy            0.028621
lily             0.027747
foxglove         0.027497
chrysanthemum    0.025622
mango            0.025372
cranberry        0.024122
iris             0.023872
allium           0.023372
peach            0.023122
cherry           0.023122
apple            0.020247
gypsophila       0.019873
wisteria         0.018373
hellebore        0.017623
hydrangea        0.015373
pear             0.010499
Name: count, dtype: float64